branch-defaults:
  default:
    environment: app-3369-env
    group_suffix: null
global:
  application_name: app-3369
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 7.4 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: null
